package/bluez5_utils: fix build with glibc < 2.25
Fix the following build failure with glibc < 2.25 raised since bump to
version 5.63 in commit d4c6cf4b1fc0f34e72ff047e76de53d3634f5184:

plugins/autopair.c:20:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

Fixes:
 - http://autobuild.buildroot.org/results/6b8870d12e0804d6154230a7322c49416c1dc0e2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>